name: Frost UI
description: "[md]![Banner](banner.png)
  
  ## A highly customizable UI"
version: 7.30.0
author: Sevii
website: https://github.com/Sevii77/frost_ui
tags:
  - Ui
dependencies: []

options:
  - Generic: 0
  
  - Foreground Color:
      description: The text and icon color
      default: [0.95, 0.95, 0.96]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Secondary Foreground Color:
      description: The opposite text color, if your text color is white, this should be black
      default: [0.0, 0.0, 0.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Accent:
      description: The pretty color used everywhere
      default: [0, 0.5, 1.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Background Color:
      description: The color of every window
      default: [0.2, 0.2, 0.23, 0.9]
      min: [0.0, 0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0, 1.0]
  
  - Secondary Color:
      description: The color of things like buttons
      default: [0.24, 0.24, 0.27]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Ternary Color:
      description: Used for rare cases like the checkbox and slider
      default: [0.7, 0.7, 0.71]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Window Style:
      description: The shape of all windows
      default: Rounded Top Border
      options:
        - Rounded:
            description: "[md]![Image](window/rounded.png)"
        - Rounded Top Border:
            inherit: Rounded
            description: "[md]![Image](window/rounded_top.png)"
        - Rounded Full Border:
            inherit: Rounded
            description: "[md]![Image](window/rounded_full.png)"
        - Rounded Edge Border:
            inherit: Rounded
            description: "[md]![Image](window/rounded_edge.png)"
        - Square:
            inherit: Rounded
            description: "[md]![Image](window/square.png)"
        - Square Top Border:
            inherit: Square
            description: "[md]![Image](window/square_top.png)"
        - Square Full Border:
            inherit: Square
            description: "[md]![Image](window/square_full.png)"
        - Square Edge Border:
            inherit: Square
            description: "[md]![Image](window/square_edge.png)"
        - Sharp:
            inherit: Square Edge Border
            description: "[md]![Image](window/sharp.png)"
    
  - Shape Style:
      description: The shape of all other things (buttons and such)
      default: Rounded
      options:
        - Rounded:
            description: "[md]![Image](shape/rounded.png)"
        - Square:
            description: "[md]![Image](shape/square.png)"
  
  - Minimap:
      default: Rounded
      options:
        - Rounded:
            description: "[md]![Image](minimap/rounded.png)"
        - Square:
            description: "[md]![Image](minimap/square.png)"
        - Circle:
            description: "[md]![Image](minimap/circle.png)"
  
  - Combat: 0
  
  - Party List Background Color:
      description: "[md]Background fade color of the partylist and alliances\n\n![Image](partylist.png)"
      default: [0.0, 0.0, 0.0, 0.0]
      min: [0.0, 0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0, 1.0]
  
  - Proc Color:
      description: "[md]The dots around actions that light up\n\n![Image](proc.png)"
      default: [1.0, 0.68, 0.22]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Shield Color:
      description: "[md]Partylist shield\n\n![Image](partyshield.png)"
      default: [0, 0.5, 1.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Castbar Color:
      description: "[md]Castbar for enemies, those you target, and partylist.\n\n![Image](castbar.png)"
      default: [0.969, 0.604, 0.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Castbar Interruptable Color:
      description: "[md]Castbar for enemies, those you target, and partylist. But whenever you can interrupt it\n\n![Image](castbar_interruptable.png)"
      default: [0.9, 0.2, 0.1]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Limit Break Charging Color:
      description: Bar color when it isn't full yet
      default: [0, 0.25, 0.5]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Limit Break Full Color:
      description: Bar color when it is full
      default: [0, 0.5, 1.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Gauge:
      description: The shape of hp/mp/job gauges
      default: Rounded
      options:
        - Rounded:
            description: "[md]![Image](gauge/rounded.png)"
        - Square:
            description: "[md]![Image](gauge/square.png)"
  
  - Gauge Background Color:
      description: The background color of hp/mp/job gauges
      default: [0.1, 0.1, 0.1, 0.6]
      min: [0.0, 0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0, 1.0]
  
  - Gauge Border Color:
      description: The border color of hp/mp/job gauges
      default: [0.15, 0.15, 0.16, 1.0]
      min: [0.0, 0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0, 1.0]
  
  - Gauge Saturation:
      description: How light or dark hp/mp/job gauges are
      default: [0.8]
      min: [0.0]
      max: [1.0]
  
  - Job icons: 0
  
  - Job Icons Content:
      default: Glow
      options:
        - Glow:
            description: "[md]![Image](job_party/glow.png)"
        - Border:
            description: "[md]![Image](job_party/border.png)"
  
  - Job Icons Party List:
      default: Glow
      options:
        - Glow:
            description: "[md]![Image](job_party/glow.png)"
        - Border:
            description: "[md]![Image](job_party/border.png)"
        - Square:
            description: "[md]![Image](job_party/square.png)"
        - Rounded:
            description: "[md]![Image](job_party/rounded.png)"
  
  - Job Icons Macro:
      default: Full
      options:
        - Glow:
            description: "[md]![Image](job_macro/glow.png)"
        - Border:
            description: "[md]![Image](job_macro/border.png)"
        - Full:
            description: "[md]![Image](job_macro/full.png)"
  
  - Pld Color:
      default: [0.231, 0.290, 0.647]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - War Color:
      default: [0.231, 0.290, 0.647]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Drk Color:
      default: [0.231, 0.290, 0.647]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Gnb Color:
      default: [0.231, 0.290, 0.647]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Whm Color:
      default: [0.231, 0.450, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Sch Color:
      default: [0.231, 0.450, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Ast Color:
      default: [0.231, 0.450, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Sge Color:
      default: [0.231, 0.450, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Mnk Color:
      default: [0.512, 0.188, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Drg Color:
      default: [0.512, 0.188, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Nin Color:
      default: [0.512, 0.188, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Sam Color:
      default: [0.512, 0.188, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Rpr Color:
      default: [0.512, 0.188, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Vpr Color:
      default: [0.512, 0.188, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Brd Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Mch Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Dnc Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Blm Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Smn Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Rdm Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Pct Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Blu Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Crp Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Bsm Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Arm Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Gsm Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Ltw Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Wvr Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Alc Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Cul Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Min Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Bot Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Fsh Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - No Job Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Job Colors:
      default: Grouped
      options:
        - Merged:
          - All:
            - Pld Color
            - War Color
            - Drk Color
            - Gnb Color
            - Whm Color
            - Sch Color
            - Ast Color
            - Sge Color
            - Mnk Color
            - Drg Color
            - Nin Color
            - Sam Color
            - Rpr Color
            - Vpr Color
            - Brd Color
            - Mch Color
            - Dnc Color
            - Blm Color
            - Smn Color
            - Rdm Color
            - Pct Color
            - Blu Color
            - Crp Color
            - Bsm Color
            - Arm Color
            - Gsm Color
            - Ltw Color
            - Wvr Color
            - Alc Color
            - Cul Color
            - Min Color
            - Bot Color
            - Fsh Color
            - No Job Color
        
        - Basic:
          - Tank Color:
            - Pld Color
            - War Color
            - Drk Color
            - Gnb Color
          - Healer Color:
            - Whm Color
            - Sch Color
            - Ast Color
            - Sge Color
          - Dps Color:
            - Mnk Color
            - Drg Color
            - Nin Color
            - Sam Color
            - Rpr Color
            - Vpr Color
            - Brd Color
            - Mch Color
            - Dnc Color
            - Blm Color
            - Smn Color
            - Rdm Color
            - Pct Color
            - Blu Color
          - Crafter Color:
            - Crp Color
            - Bsm Color
            - Arm Color
            - Gsm Color
            - Ltw Color
            - Wvr Color
            - Alc Color
            - Cul Color
          - Gatherer Color:
            - Min Color
            - Bot Color
            - Fsh Color
          - No Job Color:
            - No Job Color
        
        - Grouped:
          - Tank Color:
            - Pld Color
            - War Color
            - Drk Color
            - Gnb Color
          - Healer Color:
            - Whm Color
            - Sch Color
            - Ast Color
            - Sge Color
          - Melee Color:
            - Mnk Color
            - Drg Color
            - Nin Color
            - Sam Color
            - Rpr Color
            - Vpr Color
          - Ranged Color:
            - Brd Color
            - Mch Color
            - Dnc Color
          - Caster Color:
            - Blm Color
            - Smn Color
            - Rdm Color
            - Pct Color
            - Blu Color
          - Crafter Color:
            - Crp Color
            - Bsm Color
            - Arm Color
            - Gsm Color
            - Ltw Color
            - Wvr Color
            - Alc Color
            - Cul Color
          - Gatherer Color:
            - Min Color
            - Bot Color
            - Fsh Color
          - No Job Color:
            - No Job Color
        
        - Individual:
          - Tank: 0
          - Pld Color:
            - Pld Color
          - War Color:
            - War Color
          - Drk Color:
            - Drk Color
          - Gnb Color:
            - Gnb Color
          
          - Healer: 0
          - Whm Color:
            - Whm Color
          - Sch Color:
            - Sch Color
          - Ast Color:
            - Ast Color
          - Sge Color:
            - Sge Color
          
          - Melee: 0
          - Mnk Color:
            - Mnk Color
          - Drg Color:
            - Drg Color
          - Nin Color:
            - Nin Color
          - Sam Color:
            - Sam Color
          - Rpr Color:
            - Rpr Color
          - Vpr Color:
            - Vpr Color
          
          - Ranged: 0
          - Brd Color:
            - Brd Color
          - Mch Color:
            - Mch Color
          - Dnc Color:
            - Dnc Color
          
          - Caster: 0
          - Blm Color:
            - Blm Color
          - Smn Color:
            - Smn Color
          - Rdm Color:
            - Rdm Color
          - Pct Color:
            - Pct Color
          - Blu Color:
            - Blu Color
          
          - Crafter: 0
          - Crp Color:
            - Crp Color
          - Bsm Color:
            - Bsm Color
          - Arm Color:
            - Arm Color
          - Gsm Color:
            - Gsm Color
          - Ltw Color:
            - Ltw Color
          - Wvr Color:
            - Wvr Color
          - Alc Color:
            - Alc Color
          - Cul Color:
            - Cul Color
          
          - Gatherer: 0
          - Min Color:
            - Min Color
          - Bot Color:
            - Bot Color
          - Fsh Color:
            - Fsh Color
          
          - Other: 0
          - No Job Color:
            - No Job Color

presets:
  - Frosted:
  
  - Material UI:
      Background Color: [0.1294, 0.1294, 0.1294, 1.0]
      Secondary Color: [0.188, 0.188, 0.188]
      Window Style: Square Top Border
      Shape Style: Square
      Gauge: Square
      Minimap: Square

colors:
  1: Foreground Color
  2: [Foreground Color, Secondary Foreground Color, [0.1666, 0.1666, 0.1666]]
  3: [Foreground Color, Secondary Foreground Color, [0.3333, 0.3333, 0.3333]]
  4: [Foreground Color, Secondary Foreground Color, [0.5, 0.5, 0.5]]
  5: [Foreground Color, Secondary Foreground Color, [0.6666, 0.6666, 0.6666]]
  6: [Foreground Color, Secondary Foreground Color, [0.8333, 0.8333, 0.8333]]
  7: Secondary Foreground Color
  8: Foreground Color
  21: [Foreground Color, Secondary Foreground Color, [0.1666, 0.1666, 0.1666]]
  22: Foreground Color
  # 50: Foreground Color
  # 51: Secondary Foreground Color
  # 55: [Foreground Color, Secondary Foreground Color, [0.8333, 0.8333, 0.8333]]
  64: Foreground Color
  65: Secondary Foreground Color
  
  # custom ids only frost uses, for uld's that dont use the theme and got themed light>dark
  # TODO: look into setting a flag in the uld or smth
  7001: Foreground Color
  7002: [Foreground Color, Secondary Foreground Color, [0.1666, 0.1666, 0.1666]]
  7003: [Foreground Color, Secondary Foreground Color, [0.3333, 0.3333, 0.3333]]
  7004: [Foreground Color, Secondary Foreground Color, [0.5, 0.5, 0.5]]
  7005: [Foreground Color, Secondary Foreground Color, [0.6666, 0.6666, 0.6666]]
  7006: [Foreground Color, Secondary Foreground Color, [0.8333, 0.8333, 0.8333]]
  7007: Secondary Foreground Color

style:
  variables:
    WindowPadding: [10.0, 10.0]
    FramePadding: [8.0, 2.0]
    CellPadding: [4.0, 4.0]
    ItemSpacing: [4.0, 4.0]
    ItemInnerSpacing: [4.0, 4.0]
    # TouchExtraPadding: [2.0, 2.0]
    TouchExtraPadding: [0.0, 0.0]
    IndentSpacing: 20.0
    ScrollbarSize: 10.0
    GrabMinSize: 16.0
    
    WindowBorderSize: 2.0
    ChildBorderSize: 1.0
    PopupBorderSize: 1.0
    FrameBorderSize: 1.0
    TabBorderSize: 1.0
    
    WindowRounding:
      Window Style:
        Rounded: 11.0
        Square:  0.0
    ChildRounding:
      Shape Style:
        Rounded: 5.0
        Square:  0.0
    FrameRounding:
      Shape Style:
        Rounded: 10.0
        Square:  0.0
    PopupRounding:
      Shape Style:
        Rounded: 11.0
        Square:  0.0
    ScrollbarRounding:
      Shape Style:
        Rounded: 10.0
        Square:  0.0
    GrabRounding:
      Shape Style:
        Rounded: 12.0
        Square:  0.0
    TabRounding:
      Shape Style:
        Rounded: 5.0
        Square:  0.0
  
  colors:
    Text: Foreground Color
    TextDisabled: [Foreground Color, [0.7, 0.7, 0.7, 1.0]] # TODO: use the new gradiant type between foreground and secondary foreground
    
    WindowBg: Background Color
    ChildBg: [0.0, 0.0, 0.0, 0.0]
    PopupBg: Secondary Color
    
    Border: [Secondary Color, [0.7, 0.7, 0.7, 1.0]]
    BorderShadow: [0.0, 0.0, 0.0, 0.0]
    
    FrameBg: Secondary Color
    FrameBgHovered: [Secondary Color, [1.1, 1.1, 1.1, 1.0]]
    FrameBgActive: [Secondary Color, [1.15, 1.15, 1.15, 1.0]]
    
    TitleBg: Background Color
    TitleBgActive: Background Color
    TitleBgCollapsed: Background Color
    
    MenuBarBg: [0.0, 0.0, 0.0, 0.0]
    
    ScrollbarBg: [0.0, 0.0, 0.0, 0.0]
    ScrollbarGrab: Ternary Color
    ScrollbarGrabHovered: [Ternary Color, [1.1, 1.1, 1.1, 1.0]]
    ScrollbarGrabActive: [Ternary Color, [1.15, 1.15, 1.15, 1.0]]
    
    CheckMark: Accent
    SliderGrab: Ternary Color
    SliderGrabActive: Ternary Color
    
    Button: Secondary Color
    ButtonHovered: [Secondary Color, [1.1, 1.1, 1.1, 1.0]]
    ButtonActive: [Secondary Color, [1.15, 1.15, 1.15, 1.0]]
    
    Header: Secondary Color
    HeaderHovered: [Secondary Color, [1.1, 1.1, 1.1, 1.0]]
    HeaderActive: [Secondary Color, [1.15, 1.15, 1.15, 1.0]]
    
    Separator: [0.0, 0.0, 0.0, 0.0]
    SeparatorHovered: [Accent, [0.9, 0.9, 0.9, 1.0]]
    SeparatorActive: Accent
    
    ResizeGrip: [0.0, 0.0, 0.0, 0.0]
    ResizeGripHovered: [0.0, 0.0, 0.0, 0.0]
    ResizeGripActive: [Accent, [1.0, 1.0, 1.0, 0.5]]
    
    Tab: Secondary Color
    TabHovered: [Accent, [0.7, 0.7, 0.7, 1.0]]
    TabActive: Accent
    TabUnfocused: Secondary Color
    TabUnfocusedActive: Accent
    
    DockingPreview: Accent
    DockingEmptyBg: Secondary Color
    
    PlotLines: Accent
    PlotLinesHovered: [Accent, [0.9, 0.9, 0.9, 1.0]]
    PlotHistogram: Accent
    PlotHistogramHovered: [Accent, [0.9, 0.9, 0.9, 1.0]]
    
    TableHeaderBg: Secondary Color
    TableBorderStrong: [Secondary Color, [0.7, 0.7, 0.7, 1.0]]
    TableBorderLight: [Secondary Color, [0.8, 0.8, 0.8, 1.0]]
    TableRowBg: [0.0, 0.0, 0.0, 0.0]
    TableRowBgAlt: [0.0, 0.0, 0.0, 0.0]
    
    TextSelectedBg: Accent
    DragDropTarget: Accent
    
    NavHighlight: Accent
    NavWindowingHighlight: [1.0, 1.0, 1.0, 0.7]
    NavWindowingDimBg: [0.8, 0.8, 0.8, 0.2]
    ModalWindowDimBg: [0.8, 0.8, 0.8, 0.2]