name: Frost UI
description:
version: 0.1.56
author: Sevii
website:
tags:
  - Ui
dependencies: []

options:
  - Generic: 0
  
  - Accent:
      default: [0, 0.5, 1.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Background Color:
      default: [0.2, 0.2, 0.23, 0.9]
      min: [0.0, 0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0, 1.0]
  
  - Foreground Color:
      default: [0.95, 0.95, 0.96]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Secondary Color:
      # default: [0.6, 0.6, 0.61]
      default: [0.24, 0.24, 0.27]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Ternary Color:
      default: [0.7, 0.7, 0.71]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Window Style;Rounded Top Border:
    - Rounded
    - Rounded Top Border;Rounded
    - Rounded Full Border;Rounded
    - Rounded Edge Border;Rounded
    - Square;Rounded
    - Square Top Border;Square
    - Square Full Border;Square
    - Square Edge Border;Square
    - Sharp;Square Edge Border
    
  - Shape Style;Rounded:
    - Rounded
    - Square
  
  - Minimap;Rounded:
    - Rounded
    - Square
    - Circle
  
  - Combat: 0
  
  - Party List Background Color:
      default: [0.0, 0.0, 0.0, 0.0]
      min: [0.0, 0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0, 1.0]
  
  - Proc Color:
      default: [1.0, 0.68, 0.22]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Shield Color:
      default: [0, 0.5, 1.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Castbar Color:
      default: [0.969, 0.604, 0.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Castbar Interruptable Color:
      default: [0.9, 0.2, 0.1]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Limit Break Charging Color:
      default: [0, 0.25, 0.5]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Limit Break Full Color:
      default: [0, 0.5, 1.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Gauge;Rounded:
    - Rounded
    - Square
  
  - Gauge Background Color:
      default: [0.1, 0.1, 0.1, 0.6]
      min: [0.0, 0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0, 1.0]
  
  - Gauge Border Color:
      default: [0.15, 0.15, 0.16, 1.0]
      min: [0.0, 0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0, 1.0]
  
  - Gauge Saturation:
      default: [0.8]
      min: [0.0]
      max: [1.0]
  
  - Job icons: 0
  
  - Job Icons Content;Glow:
    - Glow
    - Border
  
  - Job Icons Party List;Glow:
    - Glow
    - Border
    - Square
    - Rounded
  
  - Job Icons Macro;Full:
    - Glow
    - Border
    - Full
  
  - Tank Color:
      default: [0.231, 0.290, 0.647]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Healer Color:
      default: [0.231, 0.450, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Melee Color:
      default: [0.512, 0.188, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Ranged Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Caster Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Crafter Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Gatherer Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - No Job Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]

presets:
  - Frosted:
  
  - Material UI:
      Background Color: [0.1294, 0.1294, 0.1294, 1.0]
      Secondary Color: [0.188, 0.188, 0.188]
      Window Style: Square Top Border
      Shape Style: Square
      Gauge: Square
      Minimap: Square

style:
  variables:
    WindowPadding: [10.0, 10.0]
    FramePadding: [8.0, 2.0]
    CellPadding: [4.0, 4.0]
    ItemSpacing: [4.0, 4.0]
    ItemInnerSpacing: [4.0, 4.0]
    # TouchExtraPadding: [2.0, 2.0]
    TouchExtraPadding: [0.0, 0.0]
    IndentSpacing: 20.0
    ScrollbarSize: 10.0
    GrabMinSize: 16.0
    
    WindowBorderSize: 2.0
    ChildBorderSize: 1.0
    PopupBorderSize: 1.0
    FrameBorderSize: 1.0
    TabBorderSize: 1.0
    
    WindowRounding:
      Window Style:
        Rounded: 11.0
        Square:  0.0
    ChildRounding:
      Shape Style:
        Rounded: 5.0
        Square:  0.0
    FrameRounding:
      Shape Style:
        Rounded: 10.0
        Square:  0.0
    PopupRounding:
      Shape Style:
        Rounded: 11.0
        Square:  0.0
    ScrollbarRounding:
      Shape Style:
        Rounded: 10.0
        Square:  0.0
    GrabRounding:
      Shape Style:
        Rounded: 12.0
        Square:  0.0
    TabRounding:
      Shape Style:
        Rounded: 5.0
        Square:  0.0
  
  colors:
    Text: Foreground Color
    TextDisabled: [Foreground Color, [0.7, 0.7, 0.7, 1.0]] # use Ternary Color when that gets implemented (maybe)
    
    WindowBg: Background Color
    ChildBg: [0.0, 0.0, 0.0, 0.0]
    PopupBg: Secondary Color
    
    Border: [Secondary Color, [0.7, 0.7, 0.7, 1.0]]
    BorderShadow: [0.0, 0.0, 0.0, 0.0]
    
    FrameBg: Secondary Color
    FrameBgHovered: [Secondary Color, [1.1, 1.1, 1.1, 1.0]]
    FrameBgActive: [Secondary Color, [1.15, 1.15, 1.15, 1.0]]
    
    TitleBg: Background Color
    TitleBgActive: Background Color
    TitleBgCollapsed: Background Color
    
    MenuBarBg: [0.0, 0.0, 0.0, 0.0]
    
    ScrollbarBg: [0.0, 0.0, 0.0, 0.0]
    ScrollbarGrab: Ternary Color
    ScrollbarGrabHovered: [Ternary Color, [1.1, 1.1, 1.1, 1.0]]
    ScrollbarGrabActive: [Ternary Color, [1.15, 1.15, 1.15, 1.0]]
    
    CheckMark: Accent
    SliderGrab: Ternary Color
    SliderGrabActive: Ternary Color
    
    Button: Secondary Color
    ButtonHovered: [Secondary Color, [1.1, 1.1, 1.1, 1.0]]
    ButtonActive: [Secondary Color, [1.15, 1.15, 1.15, 1.0]]
    
    Header: Secondary Color
    HeaderHovered: [Secondary Color, [1.1, 1.1, 1.1, 1.0]]
    HeaderActive: [Secondary Color, [1.15, 1.15, 1.15, 1.0]]
    
    Separator: [0.0, 0.0, 0.0, 0.0]
    SeparatorHovered: [Accent, [0.9, 0.9, 0.9, 1.0]]
    SeparatorActive: Accent
    
    ResizeGrip: [0.0, 0.0, 0.0, 0.0]
    ResizeGripHovered: [0.0, 0.0, 0.0, 0.0]
    ResizeGripActive: [Accent, [1.0, 1.0, 1.0, 0.5]]
    
    Tab: Secondary Color
    TabHovered: [Accent, [0.7, 0.7, 0.7, 1.0]]
    TabActive: Accent
    TabUnfocused: Secondary Color
    TabUnfocusedActive: Accent
    
    DockingPreview: Accent
    DockingEmptyBg: Secondary Color
    
    PlotLines: Accent
    PlotLinesHovered: [Accent, [0.9, 0.9, 0.9, 1.0]]
    PlotHistogram: Accent
    PlotHistogramHovered: [Accent, [0.9, 0.9, 0.9, 1.0]]
    
    TableHeaderBg: Secondary Color
    TableBorderStrong: [Secondary Color, [0.7, 0.7, 0.7, 1.0]]
    TableBorderLight: [Secondary Color, [0.8, 0.8, 0.8, 1.0]]
    TableRowBg: [0.0, 0.0, 0.0, 0.0]
    TableRowBgAlt: [0.0, 0.0, 0.0, 0.0]
    
    TextSelectedBg: Accent
    DragDropTarget: Accent
    
    NavHighlight: Accent
    NavWindowingHighlight: [1.0, 1.0, 1.0, 0.7]
    NavWindowingDimBg: [0.8, 0.8, 0.8, 0.2]
    ModalWindowDimBg: [0.8, 0.8, 0.8, 0.2]