name: Frost UI
description:
version: 0.1.51
author: Sevii
website:
tags:
  - Ui
dependencies: []
options:
  - Accent:
      default: [0, 0.5, 1.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Background Color:
      default: [0.2, 0.2, 0.23, 0.9]
      min: [0.0, 0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0, 1.0]
  
  - Foreground Color:
      default: [0.95, 0.95, 0.96]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Secondary Color:
      # default: [0.6, 0.6, 0.61]
      default: [0.24, 0.24, 0.27]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Window Style;Rounded Top Border:
    - Rounded
    - Rounded Top Border;Rounded
    - Rounded Full Border;Rounded
    - Rounded Edge Border;Rounded
    - Square;Rounded
    - Square Top Border;Square
    - Square Full Border;Square
    - Square Edge Border;Square
    - Sharp;Square Edge Border
    
  - Shape Style;Rounded:
    - Rounded
    - Square
  
  - Proc Color:
      default: [1.0, 0.68, 0.22]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Shield Color:
      default: [0, 0.5, 1.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Castbar Color:
      default: [0.969, 0.604, 0.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Castbar Interruptable Color:
      default: [0.9, 0.2, 0.1]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Limit Break Charging Color:
      default: [0, 0.25, 0.5]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Limit Break Full Color:
      default: [0, 0.5, 1.0]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Gauge;Rounded:
    - Rounded
    - Square
  
  - Job Icons Content;Glow:
    - Glow
    - Border
  
  - Job Icons Party List;Glow:
    - Glow
    - Border
    - Square
    - Rounded
  
  - Job Icons Macro;Full:
    - Glow
    - Border
    - Full
  
  - Tank Color:
      default: [0.231, 0.290, 0.647]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Healer Color:
      default: [0.231, 0.450, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Melee Color:
      default: [0.512, 0.188, 0.180]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Ranged Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Caster Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Crafter Color:
      default: [0.453, 0.265, 0.755]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Gatherer Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - No Job Color:
      default: [0.651, 0.537, 0.173]
      min: [0.0, 0.0, 0.0]
      max: [1.0, 1.0, 1.0]
  
  - Minimap;Rounded:
    - Rounded
    - Square
    - Circle
presets:
  - Frosted:
  
  - Material UI:
      Background Color: [0.1294, 0.1294, 0.1294, 1.0]
      Secondary Color: [0.188, 0.188, 0.188]
      Window Style: Square Top Border
      Shape Style: Square
      Gauge: Square
      Minimap: Square